// NodeDashboard.vue
<script>
    import {ref, onMounted} from 'vue';

    interface NetworkNode {
        id: number;
        name: string;
        status: 'online' | 'offline';
        latency: number;
    }

    const nodes = ref<NetworkNode[]>([]);
    const isLoading = ref(true);

    const highLatNodes = computed(() => {
        return nodes.value.filter(node => node.latency > 100);
    })

    onMounted(async () => {
        try {
            const res = await fetch('/api/v1/nodes');
            nodes.value = await res.json();
        } catch (error) {
            console.error("Failed to fetch nodes", error);
        } finally {
            isLoading.value = false;
        }
    });
</script>

<template>
    <div v-if="isLoading">Loading...</div>
    <div v-else v-for="node in nodes" :key="node.id">
        {{ node.name }} - {{ node.latency }}ms
    </div>
</template>

// NodeDashboard.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";

interface Node {
  id: number;
  name: string;
  latency: number;
  status: "online" | "offline";
}

const NodeDashboard = () => {
  const [nodes, setNodes] = useState<Node[]>([]);
  const [loading, setLoading] = useState<boolean>(false);

  const fetchNodes = async () => {
    setLoading(true);
    try {
      const response = await fetch("/api/v2/nodes");
      const data = response.json();
      setNodes(data);
    } catch (e) {
      console.error("Error fetching Nodes: ", e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNodes();
  }, []);

  if (loading) return <div>Optimizing loading time...</div>;

  return (
    <div>
      <ul>
        {nodes.map((node) => (
          <li key={node.id}>{node.latency}</li>
        ))}
      </ul>
    </div>
  );
};

export default NodeDashboard;
